name: deploy-storybook
on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnmpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install NodeJS dependencies
        run: pnpm install

      - name: Build Storybook
        env:
          NODE_OPTIONS: "--max_old_space_size=16384"
        run: pnpm run build-storybook

      - name: Create CNAME record file
        run: echo "yail.programmer-network" > ./storybook-static/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./storybook-static"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
